---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metabase
  namespace: flux-system
spec:
  interval: 30s
  path: ./kustomize
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: metabase
  targetNamespace: metabase
  timeout: 3m0s
  wait: true
